### ISSUE TITLE
Naquadha

### ISSUE THREAD

**Issue by stereoseven** [GT-IMPACT/IMPACT-MODPACK#376]
Какую версию модпака вы используете? / Which modpack version are you using?
1.0.1.6

Вы играете в одиночке или на сервере? / Are you playing single or on a multiplayer?
Одиночка на сервере

Опишите ошибку (Если нужно, приложите скриншоты). / Describe the bug (Attach screenshots if needed).
Naquadha Gas, "Naquadha" так и должен называться? Или это опечатка, и должно было быть "Naquadah Gas"?

Какие изменения вы предлагаете? / What changes do you suggest?
Исправить очепятку, если так быть не должно и если исправить возможно

**Comment by RaitGamerGR** [comment]
Опечатка, но уже не опечатка, а название

**Comment by Spartak1997** [comment]
Это не опечатка, а совсем другое вещество. Металл не может иметь сразу все состояния при одной температуре
